# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ThoolooExpress
email: morrill@thoolooexpress.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal blog / homepage of Richard Morrill.  Any views expressed
  here are my own, and not reflective of those of any company I currently work
  for, have worked for, or will work for in the future. Also, Git Gud.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thoolooexpress.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  ThoolooExpress
default_author: Richard Morrill
author: Richard Morrill
linkedin_username: ThoolooExpress
mastodon:
  - display_name: ThoolooExpress
    username: thoolooexpress
    instance: defcon.social

excerpt_separator: <!--more-->
show_excerpts: true

logo_url: /assets/logo.png
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

future: false

destination: docs/

exclude:
  - README.md
  - .jj/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/logo.png

# This is slightly dangerous, but a necessary evil until Minima stops using
# deprecated functions.
sass:
  quiet_deps: true
